version: '2'
services:
  rabbit1:
    #build: ./
    image: hollligan/docker-rabbitmq-cluster
    hostname: rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
      - RABBITMQ_HIPE_COMPILE=1
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbit2:
    #build: ./
    image: hollligan/docker-rabbitmq-cluster
    hostname: rabbit2
    depends_on:
      - rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
      - CLUSTER_WITH=rabbit1
      - RABBITMQ_HIPE_COMPILE=1
    ports:
      - "5673:5672"
  rabbit3:
    #build: ./
    image: hollligan/docker-rabbitmq-cluster
    hostname: rabbit3
    depends_on:
      - rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
      - CLUSTER_WITH=rabbit1
      - RABBITMQ_HIPE_COMPILE=1
    ports:
      - "5674:5672"
  rabbit4:
    #build: ./
    image: hollligan/docker-rabbitmq-cluster
    hostname: rabbit4
    depends_on:
      - rabbit1
    environment:
      - ERLANG_COOKIE=abcdefg
      - CLUSTER_WITH=rabbit1
      - RABBITMQ_HIPE_COMPILE=1
    ports:
      - "5675:5672"